### ISSUE TITLE
Support hwpstate_intel on FreeBSD 13+

### ISSUE THREAD

**Issue by NorwegianRockCat** [lonkamikaze/powerdxx#16] opened 2021-04-26 16:53 UTC
Hello,

On machines that support  the hwpstate_intel driver, powerdxx refuses to start.

```
Starting powerdxx.
powerd++: (EDRIVER) frequency control driver not supported: hwpstate_intel0
/usr/local/etc/rc.d/powerdxx: WARNING: failed to start powerdxx
```
I'm not sure which Intel CPU support this, but at least Skylake CPUs seem to have it.

**Comment by lonkamikaze** [comment] 2021-04-28 08:14
Duplicate of #15 .

**Closed as completed by lonkamikaze** 2021-04-28 08:14 UTC
